spring:
  application:
    name: tech-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sankarreddy4485/micro-environment-variable-repo.git
  
  
server:
  port: ${port:8888}
